### ISSUE TITLE
Lectura del capítulo 2

### ISSUE THREAD

**Issue by imh-02** [ULL-MII-SYTWS-2425/intro2sd-ismael-martin-herrera-alu0101397375#4]

**Comment by imh-02** [comment]
Buenos días, @crguezl, estoy tratando hace un par de días de leer el capítulo 2 del libro para la práctica pero no funciona el enlace y al buscarlo en puntoQ tampoco funciona, he probado con VPN y sin VPN. 

![Image](https://github.com/user-attachments/assets/7cc324df-d4fb-4f64-bbd7-52e0155e085a)

Saludos.

**Comment by crguezl** [comment]
@imh-02 

A mi si me deja el Punto Q.  Te contesto por email.
